name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build And push to the private repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: release
          SSH_PRIVATE_KEY: ${{ secrets.SSH_GH}}
          MESSAGE: "Commit by Github Action" # The commit message

