name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./release

  deploy:
    name: release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download production-ready build files
        uses: actions/download-artifact@v2
        with:
          name: production-files

      - name: Move public folder
        run: mv release/public ./public/

      - name: Move src folder
        run: mv release/src ./src/

      - name: Remove empty release directory
        run: rm -r release/

      - name: Set up Git
        run: |
          git config --global user.name "tranquochuy645"
          git config --global user.email "tranquochuy645@gmail.com"
          git checkout -b "release"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Deploying release files"
          git push origin "release"
